version: "3.1"

services:
  server:
    image: cpp-rest-server:latest

  client:
    image: cpp-rest-client:latest
    # We need to export the client port so that we can access the Jupyter NB
    ports:
      - 8888:8888
