version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
       pip-deps:
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
    groups:
       actions-deps:
          patterns:
            - "*"
