name: Docker images publication

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
      # This is only for test purposes... once validated, remove the branch below.
      - feat/publish-docker-images

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-rest-client:
    name: Build the ${{ matrix.image-names }} docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-names: ['python-rest-client', 'python-rest-server']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/${{ matrix.image-names }}/Dockerfile
          load: true
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ matrix.image-names }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ matrix.image-names }}:latest