name: Nightly Documentation Build

on:
  schedule:  # UTC at 0300
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  nightly_docs_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install project requirements
        run: |
          sudo apt install libeigen3-dev
          pip install -r requirements/requirements_eigen_wrapper.txt ./src/ansys/eigen/cpp/eigen-wrapper
          pip install -r requirements/requirements_build.txt .
          pip install -r requirements/requirements_docs.txt

      - name: Build documentation
        run: |
          make -C doc html
          
      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: HTML-Documentation
          path: doc/_build/html
          retention-days: 7

      - name: Deploy documentation to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.github_token }}
          branch: gh-pages
          folder: doc/_build/html
          clean: true
          single-commit: true