name: API Eigen Example - Package cleanup
on:
  workflow_dispatch:
  schedule: # UTC at 0200
    - cron: "0 2 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  cleanup:
    name: Cleaning unnecessary packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [
          'python-rest-server',
          'python-rest-client',
          'python-grpc-server',
          'python-grpc-client',
          'cpp-rest-server',
          'cpp-rest-client',
          'cpp-grpc-server',
          'cpp-grpc-client',
          ]
    env:
      PACKAGE_DELETION_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

    - name: "Perform versions cleanup - except certain tags"
      uses: pyansys/actions/hk-package-clean-except@v4
      with:
        package-org: 'ansys/api-eigen-example'
        package-name: ${{ matrix.image }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tags-kept: 'latest'
        allow-last-days: '7'
